#!/usr/bin/env bash
# script to display subdomains infos

informations ()
{
    dig_cmd=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | cut -f3- --output-delimiter=' ' | tr ' ' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $dig_cmd" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ $# -eq 1 ]; then
   informations "$1" 'www'
   informations "$1" 'lb-01'
   informations "$1" 'web-01'
   informations "$1" 'web-02'
else
   informations "$1" "$2"
fi
