#!/usr/bin/env bash
# install nginx on remote web server
# shellcheck disable=SC2154
sudo apt-get update
sudo apt-get -y install nginx
sudo /etc/init.d/nginx start
sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
